package parking.hfq.com.smartparking.model;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.title
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.desc
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.tags
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.gmt_create
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.gmt_modified
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.title
     *
     * @return the value of notice.title
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.title
     *
     * @param title the value for notice.title
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.desc
     *
     * @return the value of notice.desc
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.desc
     *
     * @param desc the value for notice.desc
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.tags
     *
     * @return the value of notice.tags
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.tags
     *
     * @param tags the value for notice.tags
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.gmt_create
     *
     * @return the value of notice.gmt_create
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.gmt_create
     *
     * @param gmtCreate the value for notice.gmt_create
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.gmt_modified
     *
     * @return the value of notice.gmt_modified
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.gmt_modified
     *
     * @param gmtModified the value for notice.gmt_modified
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}