package parking.hfq.com.smartparking.model;

public class ParkOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parkorder.id
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parkorder.carId
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    private String carid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parkorder.appointTime
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    private String appointtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parkorder.charge
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    private Float charge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parkorder.startDate
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    private String startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parkorder.startHour
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    private Integer starthour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parkorder.endDate
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    private String enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parkorder.endHour
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    private Integer endhour;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parkorder.id
     *
     * @return the value of parkorder.id
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parkorder.id
     *
     * @param id the value for parkorder.id
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parkorder.carId
     *
     * @return the value of parkorder.carId
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public String getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parkorder.carId
     *
     * @param carid the value for parkorder.carId
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public void setCarid(String carid) {
        this.carid = carid == null ? null : carid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parkorder.appointTime
     *
     * @return the value of parkorder.appointTime
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public String getAppointtime() {
        return appointtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parkorder.appointTime
     *
     * @param appointtime the value for parkorder.appointTime
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public void setAppointtime(String appointtime) {
        this.appointtime = appointtime == null ? null : appointtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parkorder.charge
     *
     * @return the value of parkorder.charge
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public Float getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parkorder.charge
     *
     * @param charge the value for parkorder.charge
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public void setCharge(Float charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parkorder.startDate
     *
     * @return the value of parkorder.startDate
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parkorder.startDate
     *
     * @param startdate the value for parkorder.startDate
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public void setStartdate(String startdate) {
        this.startdate = startdate == null ? null : startdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parkorder.startHour
     *
     * @return the value of parkorder.startHour
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public Integer getStarthour() {
        return starthour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parkorder.startHour
     *
     * @param starthour the value for parkorder.startHour
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public void setStarthour(Integer starthour) {
        this.starthour = starthour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parkorder.endDate
     *
     * @return the value of parkorder.endDate
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parkorder.endDate
     *
     * @param enddate the value for parkorder.endDate
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public void setEnddate(String enddate) {
        this.enddate = enddate == null ? null : enddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parkorder.endHour
     *
     * @return the value of parkorder.endHour
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public Integer getEndhour() {
        return endhour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parkorder.endHour
     *
     * @param endhour the value for parkorder.endHour
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public void setEndhour(Integer endhour) {
        this.endhour = endhour;
    }
}