package parking.hfq.com.smartparking.model;

import java.math.BigDecimal;

public class Parkinglot {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parkinglot.id
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parkinglot.name
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parkinglot.address
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parkinglot.picurl
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    private String picurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parkinglot.lng
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    private BigDecimal lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parkinglot.lat
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    private BigDecimal lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parkinglot.capacity
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    private Integer capacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parkinglot.available
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    private Integer available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parkinglot.id
     *
     * @return the value of parkinglot.id
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parkinglot.id
     *
     * @param id the value for parkinglot.id
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parkinglot.name
     *
     * @return the value of parkinglot.name
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parkinglot.name
     *
     * @param name the value for parkinglot.name
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parkinglot.address
     *
     * @return the value of parkinglot.address
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parkinglot.address
     *
     * @param address the value for parkinglot.address
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parkinglot.picurl
     *
     * @return the value of parkinglot.picurl
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parkinglot.picurl
     *
     * @param picurl the value for parkinglot.picurl
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parkinglot.lng
     *
     * @return the value of parkinglot.lng
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public BigDecimal getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parkinglot.lng
     *
     * @param lng the value for parkinglot.lng
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public void setLng(BigDecimal lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parkinglot.lat
     *
     * @return the value of parkinglot.lat
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public BigDecimal getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parkinglot.lat
     *
     * @param lat the value for parkinglot.lat
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public void setLat(BigDecimal lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parkinglot.capacity
     *
     * @return the value of parkinglot.capacity
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parkinglot.capacity
     *
     * @param capacity the value for parkinglot.capacity
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parkinglot.available
     *
     * @return the value of parkinglot.available
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public Integer getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parkinglot.available
     *
     * @param available the value for parkinglot.available
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public void setAvailable(Integer available) {
        this.available = available;
    }
}