package parking.hfq.com.smartparking.model;

public class ParkingSpace extends ParkingSpaceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_space.car_id
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    private String carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_space.in_use
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    private Integer inUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_space.park_time
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    private Long parkTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_space.car_id
     *
     * @return the value of parking_space.car_id
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_space.car_id
     *
     * @param carId the value for parking_space.car_id
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_space.in_use
     *
     * @return the value of parking_space.in_use
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public Integer getInUse() {
        return inUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_space.in_use
     *
     * @param inUse the value for parking_space.in_use
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public void setInUse(Integer inUse) {
        this.inUse = inUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_space.park_time
     *
     * @return the value of parking_space.park_time
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public Long getParkTime() {
        return parkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_space.park_time
     *
     * @param parkTime the value for parking_space.park_time
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    public void setParkTime(Long parkTime) {
        this.parkTime = parkTime;
    }
}