package parking.hfq.com.smartparking.model;

public class ParkingSpace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_space.id
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_space.parkinglot_id
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    private Integer parkinglotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_space.car_id
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    private String carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_space.in_use
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    private Integer inUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_space.park_time
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    private Long parkTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_space.id
     *
     * @return the value of parking_space.id
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_space.id
     *
     * @param id the value for parking_space.id
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_space.parkinglot_id
     *
     * @return the value of parking_space.parkinglot_id
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public Integer getParkinglotId() {
        return parkinglotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_space.parkinglot_id
     *
     * @param parkinglotId the value for parking_space.parkinglot_id
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public void setParkinglotId(Integer parkinglotId) {
        this.parkinglotId = parkinglotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_space.car_id
     *
     * @return the value of parking_space.car_id
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_space.car_id
     *
     * @param carId the value for parking_space.car_id
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_space.in_use
     *
     * @return the value of parking_space.in_use
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public Integer getInUse() {
        return inUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_space.in_use
     *
     * @param inUse the value for parking_space.in_use
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public void setInUse(Integer inUse) {
        this.inUse = inUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_space.park_time
     *
     * @return the value of parking_space.park_time
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public Long getParkTime() {
        return parkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_space.park_time
     *
     * @param parkTime the value for parking_space.park_time
     *
     * @mbg.generated Thu Apr 09 17:24:53 CST 2020
     */
    public void setParkTime(Long parkTime) {
        this.parkTime = parkTime;
    }
}