package parking.hfq.com.smartparking.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import parking.hfq.com.smartparking.model.ParkOrder;
import parking.hfq.com.smartparking.model.ParkOrderExample;

public interface ParkOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkorder
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    long countByExample(ParkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkorder
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    int deleteByExample(ParkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkorder
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkorder
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    int insert(ParkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkorder
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    int insertSelective(ParkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkorder
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    List<ParkOrder> selectByExampleWithRowbounds(ParkOrderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkorder
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    List<ParkOrder> selectByExample(ParkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkorder
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    ParkOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkorder
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") ParkOrder record, @Param("example") ParkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkorder
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    int updateByExample(@Param("record") ParkOrder record, @Param("example") ParkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkorder
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    int updateByPrimaryKeySelective(ParkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkorder
     *
     * @mbg.generated Thu Apr 09 00:47:46 CST 2020
     */
    int updateByPrimaryKey(ParkOrder record);
}