package parking.hfq.com.smartparking.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import parking.hfq.com.smartparking.model.ParkingSpace;
import parking.hfq.com.smartparking.model.ParkingSpaceExample;
import parking.hfq.com.smartparking.model.ParkingSpaceKey;

public interface ParkingSpaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_space
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    long countByExample(ParkingSpaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_space
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    int deleteByExample(ParkingSpaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_space
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    int deleteByPrimaryKey(ParkingSpaceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_space
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    int insert(ParkingSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_space
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    int insertSelective(ParkingSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_space
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    List<ParkingSpace> selectByExampleWithRowbounds(ParkingSpaceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_space
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    List<ParkingSpace> selectByExample(ParkingSpaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_space
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    ParkingSpace selectByPrimaryKey(ParkingSpaceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_space
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") ParkingSpace record, @Param("example") ParkingSpaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_space
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    int updateByExample(@Param("record") ParkingSpace record, @Param("example") ParkingSpaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_space
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    int updateByPrimaryKeySelective(ParkingSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_space
     *
     * @mbg.generated Thu Apr 16 21:21:39 CST 2020
     */
    int updateByPrimaryKey(ParkingSpace record);
}